/**
 * HPC Pack REST API 2016
 * This is the API spec for Microsoft HPC Pack 2016 Update 3.
 *
 * OpenAPI spec version: 2016-11-01.5.3
 * Contact: hpcpack@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Node { 
    Name?: string;
    State?: Node.StateEnum;
    Health?: Node.HealthEnum;
    Template?: string;
    Location?: string;
    MemorySize?: number;
    Cores?: number;
    Sockets?: number;
    HpcPackVersion?: string;
    OnAzure?: boolean;
    Groups?: Array<string>;
    Roles?: Array<string>;
    InstalledServiceRoles?: Array<string>;
    ActiveServiceRoles?: Array<string>;
}
export namespace Node {
    export type StateEnum = 'Unknown' | 'Provisioning' | 'Offline' | 'Starting' | 'Online' | 'Draining' | 'Rejected' | 'Removing' | 'NotDeployed' | 'Stopping';
    export const StateEnum = {
        Unknown: 'Unknown' as StateEnum,
        Provisioning: 'Provisioning' as StateEnum,
        Offline: 'Offline' as StateEnum,
        Starting: 'Starting' as StateEnum,
        Online: 'Online' as StateEnum,
        Draining: 'Draining' as StateEnum,
        Rejected: 'Rejected' as StateEnum,
        Removing: 'Removing' as StateEnum,
        NotDeployed: 'NotDeployed' as StateEnum,
        Stopping: 'Stopping' as StateEnum
    };
    export type HealthEnum = 'OK' | 'Warning' | 'Error' | 'Transitional' | 'Unapproved';
    export const HealthEnum = {
        OK: 'OK' as HealthEnum,
        Warning: 'Warning' as HealthEnum,
        Error: 'Error' as HealthEnum,
        Transitional: 'Transitional' as HealthEnum,
        Unapproved: 'Unapproved' as HealthEnum
    };
}
