/**
 * HPC Pack REST API 2016
 * This is the API spec for Microsoft HPC Pack 2016 Update 3.
 *
 * OpenAPI spec version: 2016-11-01.5.3
 * Contact: hpcpack@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface NodeGroupOperation { 
    GroupId?: number;
    Operation?: NodeGroupOperation.OperationEnum;
    NodeNames?: Array<string>;
}
export namespace NodeGroupOperation {
    export type OperationEnum = 'add' | 'remove';
    export const OperationEnum = {
        Add: 'add' as OperationEnum,
        Remove: 'remove' as OperationEnum
    };
}
