/**
 * HPC Pack REST API 2019
 * This is the API spec for Microsoft HPC Pack 2019.
 *
 * OpenAPI spec version: 2020-01-01.6.0
 * Contact: hpcpack@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type NodeServiceRole = 'HeadNode' | 'ComputeNode' | 'BrokerNode' | 'WorkstationNode' | 'AzureWorkerNode' | 'AzureVMNode' | 'UnManagedResource' | 'LinuxNode' | 'AzureBatchNode' | 'NonDomainComputeNode';

export const NodeServiceRole = {
    HeadNode: 'HeadNode' as NodeServiceRole,
    ComputeNode: 'ComputeNode' as NodeServiceRole,
    BrokerNode: 'BrokerNode' as NodeServiceRole,
    WorkstationNode: 'WorkstationNode' as NodeServiceRole,
    AzureWorkerNode: 'AzureWorkerNode' as NodeServiceRole,
    AzureVMNode: 'AzureVMNode' as NodeServiceRole,
    UnManagedResource: 'UnManagedResource' as NodeServiceRole,
    LinuxNode: 'LinuxNode' as NodeServiceRole,
    AzureBatchNode: 'AzureBatchNode' as NodeServiceRole,
    NonDomainComputeNode: 'NonDomainComputeNode' as NodeServiceRole
};
