/**
 * HPC Pack REST API 2019
 * This is the API spec for Microsoft HPC Pack 2019.
 *
 * OpenAPI spec version: 2020-01-01.6.0
 * Contact: hpcpack@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type NodeState = 'Unknown' | 'Provisioning' | 'Offline' | 'Starting' | 'Online' | 'Draining' | 'Rejected' | 'Removing' | 'NotDeployed' | 'Stopping';

export const NodeState = {
    Unknown: 'Unknown' as NodeState,
    Provisioning: 'Provisioning' as NodeState,
    Offline: 'Offline' as NodeState,
    Starting: 'Starting' as NodeState,
    Online: 'Online' as NodeState,
    Draining: 'Draining' as NodeState,
    Rejected: 'Rejected' as NodeState,
    Removing: 'Removing' as NodeState,
    NotDeployed: 'NotDeployed' as NodeState,
    Stopping: 'Stopping' as NodeState
};
