/**
 * HPC Pack REST API 2019
 * This is the API spec for Microsoft HPC Pack 2019.
 *
 * OpenAPI spec version: 2020-01-01.6.0
 * Contact: hpcpack@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NodeHealth } from './nodeHealth';
import { NodeServiceRole } from './nodeServiceRole';
import { NodeState } from './nodeState';


export interface Node { 
    Name?: string;
    State?: NodeState;
    Health?: NodeHealth;
    Template?: string;
    Location?: string;
    MemorySize?: number;
    Cores?: number;
    Sockets?: number;
    HpcPackVersion?: string;
    OnAzure?: boolean;
    Groups?: Array<string>;
    Roles?: Array<string>;
    InstalledServiceRoles?: Array<NodeServiceRole>;
    ActiveServiceRoles?: Array<NodeServiceRole>;
}
