/**
 * HPC Pack REST API 2016
 * This is the API spec for Microsoft HPC Pack 2016 Update 3.
 *
 * OpenAPI spec version: 2016-11-01.5.3
 * Contact: hpcpack@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OperationLogEntry } from './operationLogEntry';


export interface OperationLog { 
    Id?: string;
    Name?: string;
    State?: string;
    Operator?: string;
    Node?: string;
    Cancelable?: boolean;
    UpdateTime?: Date;
    Entries?: Array<OperationLogEntry>;
}
